server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/ewm-stats
    username: ewm
    password: ewm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info