server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://stats-db:5432/ewm-stats
    username: ewm
    password: ewm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO